from __future__ import annotations

import time
import uuid


def unique_value(prefix: str) -> str:
    return f"{prefix}_{int(time.time())}_{uuid.uuid4().hex[:6]}"


def category_name() -> str:
    return unique_value('CAT')


def subcategory_name() -> str:
    return unique_value('SUB')


def sku() -> str:
    return unique_value('SKU').upper()


def product_payload(category_id: int, subcategory_id: int) -> dict:
    token = unique_value('prod')
    return {
        'sku': token.upper(),
        'name': f'QA Product {token}',
        'description': 'Generated by python QA suite',
        'price': 123.45,
        'stockQty': 7,
        'imageFileName': None,
        'categoryId': category_id,
        'subCategoryId': subcategory_id,
    }
